baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Supercomputing @ UCSD"
paginate = 9
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@SuperCompUCSD"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = false
  addBang = true
  addFrame = true
  highlightColor = '#00629b'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#d31820"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
